# Generated by Django 2.2.13 on 2021-04-05 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20201003_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_url',
        ),
        migrations.CreateModel(
            name='PayPalInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_url', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_type', models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Rest', 'Rest')], max_length=30, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.Payment')),
            ],
        ),
    ]
