# Generated by Django 2.2.7 on 2019-12-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20191228_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='id_clinic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
