# Generated by Django 2.2.10 on 2020-06-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20200113_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='parent_name',
            new_name='parent_first_name',
        ),
        migrations.AddField(
            model_name='player',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('goalkeeper', 'goalkeeper'), ('defense', 'defense'), ('midfield', 'midfield'), ('forward', 'forward')], max_length=10, null=True),
        ),
    ]
