# Generated by Django 2.2.7 on 2019-12-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
