# Generated by Django 2.2.7 on 2019-12-18 14:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_tripinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=7),
        ),
    ]
