# Generated by Django 2.2.7 on 2019-12-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_auto_20191228_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripinvitation',
            name='additional_players',
            field=models.ManyToManyField(blank=True, related_name='additional_players', to='players.Player'),
        ),
        migrations.AlterField(
            model_name='tripinvitation',
            name='companions',
            field=models.ManyToManyField(blank=True, to='trips.TripCompanion'),
        ),
    ]
