# Generated by Django 2.2.7 on 2020-04-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0014_tripdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="email_files",
            field=models.ManyToManyField(to="trips.TripDocument"),
        ),
    ]
