# Generated by Django 2.2.7 on 2020-05-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_auto_20200404_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='email_files',
            field=models.ManyToManyField(blank=True, to='trips.TripDocument'),
        ),
    ]
