# Generated by Django 2.2.10 on 2020-07-08 21:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_auto_20200507_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripinvitation',
            name='additional_players',
        ),
        migrations.RemoveField(
            model_name='tripinvitation',
            name='companions',
        ),
        migrations.AddField(
            model_name='tripinvitation',
            name='form_information',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
