# Generated by Django 2.2.10 on 2020-09-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_auto_20200906_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripinvitation',
            name='status',
            field=models.CharField(choices=[('Invite Sent', 'Invite Sent'), ('Started', 'Started'), ('Player Data Filled', 'Player Data Filled'), ('Companion Data Filled', 'Companion Data Filled'), ('Terms Agreed', 'Terms Agreed'), ('Invoice Sent', 'Invoice Sent'), ('Deposit Paid', 'Deposit Paid'), ('Paid', 'Paid')], default='Invite Sent', max_length=30),
        ),
    ]
