# Generated by Django 2.2.10 on 2020-09-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_auto_20200906_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('terms_and_conditions', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
