# Generated by Django 2.2.10 on 2020-10-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_tripterms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripterms',
            options={'verbose_name_plural': 'trip terms'},
        ),
        migrations.AddField(
            model_name='tripinvitation',
            name='terms_signature',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
