# Generated by Django 2.2.10 on 2020-10-03 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0023_auto_20201003_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripinvitation',
            name='terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trips.TripTerms'),
        ),
    ]
