# Generated by Django 2.2.10 on 2020-10-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0024_tripinvitation_terms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripCompanion',
        ),
    ]
