# Generated by Django 2.2.13 on 2021-03-15 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0025_delete_tripcompanion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripinvitation',
            name='terms_accepted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 13, 55, 56, 639759, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
