# Generated by Django 2.2.13 on 2021-03-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0026_tripinvitation_terms_accepted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripinvitation',
            name='terms_accepted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
