# Generated by Django 2.2.13 on 2021-06-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0028_trip_deposit_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripInvitationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='player_uploads/')),
                ('trip_invitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.TripInvitation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
