# Generated by Django 2.2.13 on 2021-09-21 20:14

from django.db import migrations, models
import django.db.models.deletion
import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0029_tripinvitationfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('terms_name', models.CharField(max_length=30)),
                ('custom_terms', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Custom Terms',
            },
        ),
        migrations.AlterField(
            model_name='tripinvitationfile',
            name='document',
            field=models.FileField(upload_to=trips.models.get_trip_invitation_file_path),
        ),
        migrations.AddField(
            model_name='trip',
            name='additional_terms',
            field=models.ForeignKey(blank=True, help_text='Selected additional terms and conditions will appear on T&C step', null=True, on_delete=django.db.models.deletion.PROTECT, to='trips.CustomTerm'),
        ),
    ]
