# Generated by Django 2.2.13 on 2021-09-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0030_auto_20210921_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomTerm',
            new_name='TripCustomTerm',
        ),
    ]
