# Generated by Django 2.2.13 on 2021-09-21 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0031_auto_20210921_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripcustomterm',
            options={'verbose_name_plural': 'Trip Custom Terms'},
        ),
        migrations.AddField(
            model_name='tripinvitation',
            name='additional_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trips.TripCustomTerm'),
        ),
    ]
