# Generated by Django 2.2.13 on 2021-10-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('trips', '0032_auto_20210921_2035')]

    operations = [
        migrations.AddField(
            model_name='tripinvitation',
            name='terms_names',
            field=models.CharField(default=None, max_length=30, blank=True, null=True),
            preserve_default=False,
        )
    ]
